### ISSUE TITLE
Unable to publish to specific destination

### ISSUE THREAD

**Issue by jloosli** [chabad360/hugo-gh-pages#12]
I'd like to have this build in the the `/docs` directory of the `master` branch. My config file is as follows:

```yaml
name: Hugo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Create /docs directory
        run: |
          rm -rf ./docs
          mkdir ./docs

      - name: Build and Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.BUILD_TOKEN }}
          branch: master
```

I also have the following in my `config.toml`:
```
publishDir = "docs"
```

When run locally, this works well and publishes to the `/docs` directory. However, when the action runs on github, it builds successfully, but at the root of my repository which is what I don't want to happen. I've tried overriding this with the `args` parameter:

```
args: --gc --minify --cleanDestinationDir --verbose --destination=docs
```

For what it's worth, I've tried the following variations for destination that all have the same result:
```
docs
/docs
${{ github.workspace }}/docs
```

However, I still get the same results. Is this a bug, or am I configured incorrectly?
